
-- Create medical_journals table to store the curated whitelist of 100 journals
CREATE TABLE IF NOT EXISTS public.medical_journals (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  publisher TEXT,
  category TEXT NOT NULL,
  url TEXT NOT NULL,
  impact_factor NUMERIC,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.medical_journals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read medical journals"
  ON public.medical_journals FOR SELECT
  USING (true);

CREATE INDEX IF NOT EXISTS idx_medical_journals_category ON public.medical_journals(category);

-- Insert 100 curated medical journals
INSERT INTO public.medical_journals (name, publisher, category, url, impact_factor, description) VALUES
('The New England Journal of Medicine', 'Massachusetts Medical Society', 'General Medicine', 'https://www.nejm.org', 158.5, 'Premier weekly general medical journal'),
('The Lancet', 'Elsevier', 'General Medicine', 'https://www.thelancet.com', 168.9, 'Weekly peer-reviewed general medical journal'),
('JAMA - Journal of the American Medical Association', 'American Medical Association', 'General Medicine', 'https://jamanetwork.com/journals/jama', 120.7, 'Peer-reviewed general medical journal'),
('BMJ - British Medical Journal', 'BMJ Group', 'General Medicine', 'https://www.bmj.com', 105.7, 'Weekly general medical journal'),
('Nature Medicine', 'Nature Publishing Group', 'General Medicine', 'https://www.nature.com/nm', 87.2, 'Translational medical research'),
('Annals of Internal Medicine', 'American College of Physicians', 'Internal Medicine', 'https://www.acpjournals.org/journal/aim', 39.2, 'Internal medicine clinical research'),
('Cell', 'Cell Press', 'Biomedical Research', 'https://www.cell.com', 66.8, 'Biological sciences research'),
('Science Translational Medicine', 'AAAS', 'Translational Medicine', 'https://www.science.org/journal/stm', 19.3, 'Translational research journal'),
('PLOS Medicine', 'Public Library of Science', 'General Medicine', 'https://journals.plos.org/plosmedicine', 15.8, 'Open access general medicine'),
('Cochrane Database of Systematic Reviews', 'Cochrane Collaboration', 'Evidence-Based Medicine', 'https://www.cochranelibrary.com', 12.0, 'Systematic reviews of healthcare interventions'),
('Mayo Clinic Proceedings', 'Mayo Foundation', 'General Medicine', 'https://www.mayoclinicproceedings.org', 9.0, 'Peer-reviewed clinical journal'),
('CMAJ - Canadian Medical Association Journal', 'CMA', 'General Medicine', 'https://www.cmaj.ca', 9.4, 'Canadian general medical research'),
('PubMed Central', 'NCBI/NIH', 'Database', 'https://www.ncbi.nlm.nih.gov/pmc', NULL, 'Free archive of biomedical literature'),
('Circulation', 'AHA', 'Cardiology', 'https://www.ahajournals.org/journal/circ', 39.9, 'Cardiovascular research'),
('Journal of the American College of Cardiology', 'Elsevier', 'Cardiology', 'https://www.jacc.org', 27.2, 'Cardiology research'),
('European Heart Journal', 'Oxford Academic', 'Cardiology', 'https://academic.oup.com/eurheartj', 39.3, 'European cardiology'),
('Heart', 'BMJ', 'Cardiology', 'https://heart.bmj.com', 7.3, 'Cardiovascular medicine'),
('JAMA Cardiology', 'AMA', 'Cardiology', 'https://jamanetwork.com/journals/jamacardiology', 24.0, 'Cardiology research'),
('American Journal of Cardiology', 'Elsevier', 'Cardiology', 'https://www.ajconline.org', 2.8, 'Clinical cardiology'),
('JAMA Neurology', 'AMA', 'Neurology', 'https://jamanetwork.com/journals/jamaneurology', 29.0, 'Neurology research'),
('Neurology', 'AAN', 'Neurology', 'https://www.neurology.org', 9.9, 'Clinical neurology research'),
('Brain', 'Oxford Academic', 'Neurology', 'https://academic.oup.com/brain', 14.5, 'Neurology and neuroscience'),
('Lancet Neurology', 'Elsevier', 'Neurology', 'https://www.thelancet.com/journals/laneur', 48.0, 'Neurological research'),
('Annals of Neurology', 'Wiley', 'Neurology', 'https://onlinelibrary.wiley.com/journal/15318249', 11.2, 'Neurology research'),
('Stroke', 'AHA', 'Neurology', 'https://www.ahajournals.org/journal/str', 8.4, 'Cerebrovascular disease research'),
('Lancet Oncology', 'Elsevier', 'Oncology', 'https://www.thelancet.com/journals/lanonc', 51.1, 'Cancer research'),
('Journal of Clinical Oncology', 'ASCO', 'Oncology', 'https://ascopubs.org/journal/jco', 45.3, 'Clinical oncology'),
('JAMA Oncology', 'AMA', 'Oncology', 'https://jamanetwork.com/journals/jamaoncology', 28.4, 'Oncology research'),
('Cancer Cell', 'Cell Press', 'Oncology', 'https://www.cell.com/cancer-cell', 50.3, 'Cancer biology'),
('Nature Reviews Cancer', 'Nature', 'Oncology', 'https://www.nature.com/nrc', 78.5, 'Cancer research reviews'),
('CA: A Cancer Journal for Clinicians', 'ACS', 'Oncology', 'https://acsjournals.onlinelibrary.wiley.com/journal/15424863', 254.7, 'Cancer statistics and reviews'),
('Diabetes Care', 'ADA', 'Endocrinology', 'https://diabetesjournals.org/care', 16.2, 'Diabetes research'),
('Diabetes', 'ADA', 'Endocrinology', 'https://diabetesjournals.org/diabetes', 7.7, 'Diabetes basic and clinical research'),
('Lancet Diabetes Endocrinology', 'Elsevier', 'Endocrinology', 'https://www.thelancet.com/journals/landia', 44.5, 'Diabetes and endocrine research'),
('Journal of Clinical Endocrinology and Metabolism', 'Endocrine Society', 'Endocrinology', 'https://academic.oup.com/jcem', 5.8, 'Endocrinology research'),
('Endocrine Reviews', 'Endocrine Society', 'Endocrinology', 'https://academic.oup.com/edrv', 22.0, 'Endocrinology reviews'),
('Gastroenterology', 'AGA', 'Gastroenterology', 'https://www.gastrojournal.org', 33.9, 'GI research'),
('Gut', 'BMJ', 'Gastroenterology', 'https://gut.bmj.com', 24.5, 'Gastroenterology and hepatology'),
('Hepatology', 'AASLD', 'Gastroenterology', 'https://aasldpubs.onlinelibrary.wiley.com/journal/15273350', 13.5, 'Liver disease research'),
('American Journal of Gastroenterology', 'Wolters Kluwer', 'Gastroenterology', 'https://journals.lww.com/ajg', 9.8, 'Clinical GI'),
('Lancet Gastroenterology Hepatology', 'Elsevier', 'Gastroenterology', 'https://www.thelancet.com/journals/langas', 30.9, 'GI and liver research'),
('American Journal of Respiratory and Critical Care Medicine', 'ATS', 'Pulmonology', 'https://www.atsjournals.org/journal/ajrccm', 24.7, 'Respiratory and critical care'),
('Chest', 'Elsevier', 'Pulmonology', 'https://journal.chestnet.org', 9.6, 'Pulmonology and critical care'),
('Lancet Respiratory Medicine', 'Elsevier', 'Pulmonology', 'https://www.thelancet.com/journals/lanres', 76.2, 'Respiratory medicine'),
('European Respiratory Journal', 'ERS', 'Pulmonology', 'https://erj.ersjournals.com', 24.3, 'Respiratory research'),
('Thorax', 'BMJ', 'Pulmonology', 'https://thorax.bmj.com', 10.0, 'Respiratory medicine'),
('Lancet Infectious Diseases', 'Elsevier', 'Infectious Diseases', 'https://www.thelancet.com/journals/laninf', 56.3, 'Infectious disease research'),
('Clinical Infectious Diseases', 'Oxford Academic', 'Infectious Diseases', 'https://academic.oup.com/cid', 11.8, 'Clinical infectious disease'),
('Journal of Infectious Diseases', 'Oxford Academic', 'Infectious Diseases', 'https://academic.oup.com/jid', 5.0, 'Infectious disease research'),
('Emerging Infectious Diseases', 'CDC', 'Infectious Diseases', 'https://wwwnc.cdc.gov/eid', 11.8, 'Emerging infections'),
('AIDS', 'Wolters Kluwer', 'Infectious Diseases', 'https://journals.lww.com/aidsonline', 4.0, 'HIV/AIDS research'),
('Pediatrics', 'AAP', 'Pediatrics', 'https://publications.aap.org/pediatrics', 8.0, 'Pediatric medicine'),
('JAMA Pediatrics', 'AMA', 'Pediatrics', 'https://jamanetwork.com/journals/jamapediatrics', 24.7, 'Pediatric research'),
('Lancet Child Adolescent Health', 'Elsevier', 'Pediatrics', 'https://www.thelancet.com/journals/lanchi', 36.4, 'Child health research'),
('Archives of Disease in Childhood', 'BMJ', 'Pediatrics', 'https://adc.bmj.com', 5.4, 'Pediatric medicine'),
('Journal of Pediatrics', 'Elsevier', 'Pediatrics', 'https://www.jpeds.com', 4.0, 'Pediatric clinical research'),
('Obstetrics and Gynecology', 'Wolters Kluwer', 'Obstetrics-Gynecology', 'https://journals.lww.com/greenjournal', 7.2, 'Ob/Gyn research'),
('American Journal of Obstetrics and Gynecology', 'Elsevier', 'Obstetrics-Gynecology', 'https://www.ajog.org', 9.8, 'Ob/Gyn research'),
('Human Reproduction', 'Oxford Academic', 'Obstetrics-Gynecology', 'https://academic.oup.com/humrep', 6.1, 'Reproductive medicine'),
('Lancet Psychiatry', 'Elsevier', 'Psychiatry', 'https://www.thelancet.com/journals/lanpsy', 64.3, 'Psychiatry research'),
('JAMA Psychiatry', 'AMA', 'Psychiatry', 'https://jamanetwork.com/journals/jamapsychiatry', 25.8, 'Psychiatric research'),
('American Journal of Psychiatry', 'APA', 'Psychiatry', 'https://ajp.psychiatryonline.org', 19.2, 'Psychiatry research'),
('British Journal of Psychiatry', 'Cambridge', 'Psychiatry', 'https://www.cambridge.org/core/journals/the-british-journal-of-psychiatry', 10.7, 'Psychiatric medicine'),
('Molecular Psychiatry', 'Nature', 'Psychiatry', 'https://www.nature.com/mp', 11.0, 'Psychiatric research'),
('JAMA Dermatology', 'AMA', 'Dermatology', 'https://jamanetwork.com/journals/jamadermatology', 11.5, 'Dermatology research'),
('Journal of the American Academy of Dermatology', 'Elsevier', 'Dermatology', 'https://www.jaad.org', 12.8, 'Dermatology clinical research'),
('British Journal of Dermatology', 'Wiley', 'Dermatology', 'https://onlinelibrary.wiley.com/journal/13652133', 11.1, 'Dermatology research'),
('JAMA Ophthalmology', 'AMA', 'Ophthalmology', 'https://jamanetwork.com/journals/jamaophthalmology', 8.1, 'Ophthalmology research'),
('Ophthalmology', 'Elsevier', 'Ophthalmology', 'https://www.aaojournal.org', 14.0, 'Ophthalmology clinical research'),
('Kidney International', 'Elsevier', 'Nephrology', 'https://www.kidney-international.org', 19.6, 'Nephrology research'),
('Journal of the American Society of Nephrology', 'ASN', 'Nephrology', 'https://jasn.asnjournals.org', 13.6, 'Nephrology research'),
('Lancet Rheumatology', 'Elsevier', 'Rheumatology', 'https://www.thelancet.com/journals/lanrhe', 22.0, 'Rheumatology research'),
('Annals of the Rheumatic Diseases', 'BMJ', 'Rheumatology', 'https://ard.bmj.com', 27.4, 'Rheumatology research'),
('Arthritis Rheumatology', 'Wiley', 'Rheumatology', 'https://onlinelibrary.wiley.com/journal/23265205', 13.3, 'Arthritis research'),
('Blood', 'ASH', 'Hematology', 'https://ashpublications.org/blood', 25.4, 'Hematology research'),
('Lancet Haematology', 'Elsevier', 'Hematology', 'https://www.thelancet.com/journals/lanhae', 24.7, 'Hematology research'),
('Annals of Surgery', 'Wolters Kluwer', 'Surgery', 'https://journals.lww.com/annalsofsurgery', 13.8, 'Surgical research'),
('JAMA Surgery', 'AMA', 'Surgery', 'https://jamanetwork.com/journals/jamasurgery', 16.9, 'Surgical research'),
('British Journal of Surgery', 'Oxford Academic', 'Surgery', 'https://academic.oup.com/bjs', 11.1, 'Surgical research'),
('Anesthesiology', 'Wolters Kluwer', 'Anesthesiology', 'https://pubs.asahq.org/anesthesiology', 9.1, 'Anesthesiology research'),
('British Journal of Anaesthesia', 'Elsevier', 'Anesthesiology', 'https://www.bjanaesthesia.org', 9.8, 'Anesthesia research'),
('Critical Care Medicine', 'Wolters Kluwer', 'Critical Care', 'https://journals.lww.com/ccmjournal', 8.8, 'Intensive care research'),
('Intensive Care Medicine', 'Springer', 'Critical Care', 'https://link.springer.com/journal/134', 27.1, 'Critical care research'),
('Annals of Emergency Medicine', 'Elsevier', 'Emergency Medicine', 'https://www.annemergmed.com', 6.1, 'Emergency medicine research'),
('Academic Emergency Medicine', 'Wiley', 'Emergency Medicine', 'https://onlinelibrary.wiley.com/journal/15532712', 4.4, 'Emergency medicine'),
('American Journal of Public Health', 'APHA', 'Public Health', 'https://ajph.aphapublications.org', 12.0, 'Public health research'),
('Lancet Public Health', 'Elsevier', 'Public Health', 'https://www.thelancet.com/journals/lanpub', 50.0, 'Public health research'),
('WHO Bulletin', 'World Health Organization', 'Public Health', 'https://www.who.int/publications/journals/bulletin', 8.5, 'Global public health'),
('Lancet Global Health', 'Elsevier', 'Public Health', 'https://www.thelancet.com/journals/langlo', 34.3, 'Global health research'),
('NICE Guidelines', 'National Institute for Health and Care Excellence', 'Clinical Guidelines', 'https://www.nice.org.uk/guidance', NULL, 'UK clinical practice guidelines'),
('CDC MMWR', 'Centers for Disease Control', 'Public Health', 'https://www.cdc.gov/mmwr', 24.4, 'Morbidity and mortality reports'),
('USPSTF Recommendations', 'US Preventive Services Task Force', 'Clinical Guidelines', 'https://www.uspreventiveservicestaskforce.org', NULL, 'Preventive care recommendations'),
('Journal of Bone and Joint Surgery', 'Wolters Kluwer', 'Orthopedics', 'https://journals.lww.com/jbjsjournal', 5.3, 'Orthopedic surgery research'),
('Bone Joint Journal', 'BMJ', 'Orthopedics', 'https://boneandjoint.org.uk', 4.9, 'Orthopedic research'),
('Journal of Urology', 'Wolters Kluwer', 'Urology', 'https://www.auajournals.org/journal/juro', 7.6, 'Urology research'),
('European Urology', 'Elsevier', 'Urology', 'https://www.europeanurology.com', 25.3, 'Urological research'),
('Journal of Allergy and Clinical Immunology', 'Elsevier', 'Allergy-Immunology', 'https://www.jacionline.org', 14.2, 'Allergy and immunology research'),
('Allergy', 'Wiley', 'Allergy-Immunology', 'https://onlinelibrary.wiley.com/journal/13989995', 12.6, 'Allergy research'),
('Headache', 'Wiley', 'Neurology', 'https://onlinelibrary.wiley.com/journal/15264610', 5.4, 'Headache and migraine research'),
('Pain', 'Wolters Kluwer', 'Pain Medicine', 'https://journals.lww.com/pain', 7.4, 'Pain research'),
('Sleep', 'Oxford Academic', 'Sleep Medicine', 'https://academic.oup.com/sleep', 5.6, 'Sleep medicine research'),
('Nutrition Reviews', 'Oxford Academic', 'Nutrition', 'https://academic.oup.com/nutritionreviews', 6.2, 'Nutrition science reviews'),
('American Journal of Clinical Nutrition', 'Elsevier', 'Nutrition', 'https://academic.oup.com/ajcn', 7.1, 'Clinical nutrition research')
ON CONFLICT DO NOTHING;

-- Update RLS for user_actions to require user_id when authenticated; keep insert open for anonymous tracking
-- (Keep existing policies but ensure UPDATE/DELETE remain disallowed)
